default: &default
  title: Hepte
  host: hepte.com

  mailer:
    # For localhost postfix
    smtp_settings:
      address: localhost
      port: 25
      enable_starttls_auto: false
      #domain:
      #user_name:
      #password:
      #authentication:
    default_options:
      from: no-reply@hepte.com
    default_url_options:
      host: hepte.com
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
  elasticsearch:
    host: localhost:9200

development:
  <<: *default
  admin_emails:
    - admin@hepte.com

test:
  <<: *default
  admin_emails:
    - admin@hepte.com

production:
  <<: *default

  admin_emails:
    - yasin@hepte.com
